In [19]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

#### import our package

In [20]:
df = pd.read_csv("C:/Users/Aslam Khan/Desktop/SalaryData_Train(1).csv")

# EDA- Exploratery data analysis

In [21]:
df.head()### we have define five first row our data

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [114]:
df.tail()## we have define last five row of our data

age      workclass    education  educationno        maritalstatus  \
30156   27        Private   Assoc-acdm           12   Married-civ-spouse   
30157   40        Private      HS-grad            9   Married-civ-spouse   
30158   58        Private      HS-grad            9              Widowed   
30159   22        Private      HS-grad            9        Never-married   
30160   52   Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation relationship    race      sex  capitalgain  \
30156        Tech-support         Wife   White   Female            0   
30157   Machine-op-inspct      Husband   White     Male            0   
30158        Adm-clerical    Unmarried   White   Female            0   
30159        Adm-clerical    Own-child   White     Male            0   
30160     Exec-managerial         Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K

In [22]:
df.shape### we have define the row and columns our data

(30161, 14)

In [23]:
df.columns  ## define the columns

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [115]:
 df.info()## define the nulll values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [25]:
df.isnull().sum()## find the mising values

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [26]:
df.describe()## define the nuemeric statistic

age   educationno   capitalgain   capitalloss  hoursperweek
count  30161.000000  30161.000000  30161.000000  30161.000000  30161.000000
mean      38.438115     10.121316   1092.044064     88.302311     40.931269
std       13.134830      2.550037   7406.466611    404.121321     11.980182
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   4356.000000     99.000000

In [27]:
x = df[['age','educationno','capitalgain','capitalloss','hoursperweek']]### define the x and y variable
y = df[['age']]


In [28]:
x

age  educationno  capitalgain  capitalloss  hoursperweek
0       39           13         2174            0            40
1       50           13            0            0            13
2       38            9            0            0            40
3       53            7            0            0            40
4       28           13            0            0            40
...    ...          ...          ...          ...           ...
30156   27           12            0            0            38
30157   40            9            0            0            40
30158   58            9            0            0            40
30159   22            9            0            0            20
30160   52            9        15024            0            40

[30161 rows x 5 columns]

In [29]:
y

age
0       39
1       50
2       38
3       53
4       28
...    ...
30156   27
30157   40
30158   58
30159   22
30160   52

[30161 rows x 1 columns]

In [30]:
x = x.values.reshape(-1,1)###  reshape our data
x

array([[   39],
       [   13],
       [ 2174],
       ...,
       [15024],
       [    0],
       [   40]], dtype=int64)

In [31]:
y = y.values.reshape(-1,1)
y

array([[39],
       [50],
       [38],
       ...,
       [58],
       [22],
       [52]], dtype=int64)

In [118]:
x = df.iloc[:,0:1]
x

age
0       39
1       50
2       38
3       53
4       28
...    ...
30156   27
30157   40
30158   58
30159   22
30160   52

[30161 rows x 1 columns]

In [84]:
y = df.iloc[:,:1]
y

age
0       39
1       50
2       38
3       53
4       28
...    ...
30156   27
30157   40
30158   58
30159   22
30160   52

[30161 rows x 1 columns]

In [85]:
#x

### we have splitting  our data training and testing

In [87]:
## we have splitting  our data training and testing
from sklearn.model_selection import train_test_split

In [88]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=1234)

In [89]:
x_train

array([[58],
       [49],
       [51],
       ...,
       [28],
       [25],
       [60]], dtype=int64)

In [90]:
y_train

age
4743    58
25659   49
18414   51
25160   33
6874    53
...    ...
27852   36
23605   23
1318    28
25299   25
27439   60

[24128 rows x 1 columns]

In [91]:
x_train.shape

(24128, 1)

In [92]:
y_train.shape

(24128, 1)

# we have import our package 

In [96]:
from sklearn.svm import SVC

In [98]:
model = SVC(kernel='linear')
model

SVC(kernel='linear')

In [ ]:
#### we have fit our data for modeling

In [106]:
 svc = model.fit(x_train,y_train)

C:\Users\Aslam Khan\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# we have predict  our data

In [107]:
pred = model.predict(x_test)
pred

array([37, 54, 36, ..., 39, 21, 22], dtype=int64)

#### define the r2_score value and condfusion matrix

In [102]:
from sklearn.metrics import r2_score
from sklearn.metrics import confusion_matrix,   ConfusionMatrixDisplay, classification_report,accuracy_score

In [103]:
confusion_matrix(y_test,pred)

array([[ 55,   0,   0, ...,   0,   0,   0],
       [  0,  85,   0, ...,   0,   0,   0],
       [  0,   0, 111, ...,   0,   0,   0],
       ...,
       [  0,   0,   0, ...,   2,   0,   0],
       [  0,   0,   0, ...,   0,   1,   0],
       [  0,   0,   0, ...,   0,   0,   6]], dtype=int64)

### define the accuracy score our data

In [104]:
accuracy_score(y_test,pred)

1.0

In [105]:
### for saving the model
import pickle

In [109]:
saved_model = pickle.dumps(svc) 
saved_model

b'\x80\x04\x95v\x0f\x00\x00\x00\x00\x00\x00\x8c\x14sklearn.svm._classes\x94\x8c\x03SVC\x94\x93\x94)\x81\x94}\x94(\x8c\x17decision_function_shape\x94\x8c\x03ovr\x94\x8c\nbreak_ties\x94\x89\x8c\x06kernel\x94\x8c\x06linear\x94\x8c\x06degree\x94K\x03\x8c\x05gamma\x94\x8c\x05scale\x94\x8c\x05coef0\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x03tol\x94G?PbM\xd2\xf1\xa9\xfc\x8c\x01C\x94G?\xf0\x00\x00\x00\x00\x00\x00\x8c\x02nu\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\x07epsilon\x94G\x00\x00\x00\x00\x00\x00\x00\x00\x8c\tshrinking\x94\x88\x8c\x0bprobability\x94\x89\x8c\ncache_size\x94K\xc8\x8c\x0cclass_weight\x94N\x8c\x07verbose\x94\x89\x8c\x08max_iter\x94J\xff\xff\xff\xff\x8c\x0crandom_state\x94N\x8c\x07_sparse\x94\x89\x8c\x0en_features_in_\x94K\x01\x8c\rclass_weight_\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01KH\x85\x94h\x1f\x8c\x05dtype\x94\x93\x94\x8c\x02f8\x94\x89\x88\x87\x94R\x94(K\x

In [111]:
svm_pickle = pickle.loads(saved_model)

In [112]:
svm_pickle.predict(x_test)

array([37, 54, 36, ..., 39, 21, 22], dtype=int64)

In [113]:
### done 